# Generated by Django 3.2.2 on 2021-05-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_chef',
            field=models.BooleanField(default=False),
        ),
    ]
