# Generated by Django 3.2.2 on 2021-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='defaulty.png', upload_to='images/'),
        ),
    ]
