# Generated by Django 3.2.2 on 2021-05-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_chef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profic_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='tina.jpg', null=True, upload_to=''),
        ),
    ]
