# Generated by Django 3.2.2 on 2021-05-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_application_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active')], default='Pending', max_length=30),
        ),
    ]
