# Generated by Django 3.2.2 on 2021-05-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Denied', 'Dinied')], default='Pending', max_length=30),
        ),
    ]
