# Generated by Django 3.2.2 on 2021-05-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_letter',
            field=models.ImageField(blank=True, default='Blank.png', null=True, upload_to='letter_files'),
        ),
    ]
