# Generated by Django 3.2.2 on 2021-05-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_application_app_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_letter',
            field=models.ImageField(blank=True, default='next.png', upload_to='letter_files'),
        ),
    ]
