# Generated by Django 3.2.2 on 2021-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_application_app_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Africa Cuisine', 'African Cuisine'), ('Mediterian Cuisine', 'Mediterian Cuisine'), ('American Cuisine', 'American Cuisine'), ('none', 'none')], default='none', max_length=30),
        ),
    ]
