# Generated by Django 3.2.2 on 2021-05-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_application_app_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Denied', 'Denied')], default='Pending', max_length=30),
        ),
    ]
