# Generated by Django 3.2.2 on 2021-05-28 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateField(default=datetime.datetime(2021, 5, 28, 9, 44, 47, 448031))),
                ('status', models.CharField(choices=[('available', 'available'), ('taken', 'taken'), ('notavailable', 'notavailable')], default='available', max_length=30, null=True)),
                ('user_chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('meal_image', models.ImageField(blank=True, default='food.png', upload_to='meals')),
                ('description', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Lunch', 'Lunch'), ('BreakFast', 'BreakFast'), ('Dinner', 'Dinner')], default='Dinner', max_length=40)),
                ('Calories', models.CharField(blank=True, max_length=40, null=True)),
                ('user_chef', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('numberOfPeople', models.IntegerField(null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('meals', models.CharField(blank=True, max_length=40, null=True)),
                ('add_info', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.schedule')),
            ],
        ),
    ]
