# Generated by Django 3.2.2 on 2021-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment',
        ),
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_image',
            field=models.ImageField(blank=True, upload_to='meals/'),
        ),
    ]
