# Generated by Django 3.2.2 on 2021-05-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210515_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_image',
            field=models.ImageField(blank=True, default='food.png', upload_to='meals/'),
        ),
    ]
