# Generated by Django 3.2.2 on 2021-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('notavailable', 'notavailable')], default='available', max_length=30),
        ),
    ]
