# Generated by Django 3.2.2 on 2021-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210520_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_image',
            field=models.ImageField(blank=True, default=None, upload_to='meals'),
        ),
    ]
