# Generated by Django 3.2.2 on 2021-05-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_meal_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
