# Generated by Django 3.2.2 on 2021-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hour',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('taken', 'taken'), ('notavailable', 'notavailable')], default='available', max_length=30, null=True),
        ),
    ]
