# Generated by Django 3.2.2 on 2021-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meals',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
