# Generated by Django 3.2.2 on 2021-05-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_booking_meals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='price',
            new_name='Calories',
        ),
    ]
