# Generated by Django 3.2.2 on 2021-05-26 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20210526_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 20, 13, 38, 912921)),
        ),
    ]
