# Generated by Django 3.2.2 on 2021-05-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_rename_price_meal_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='add_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
