# Generated by Django 3.2.2 on 2021-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_booking_add_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='Calories',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
